// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB73EHIrYFB_wsZHg-WLRRANw2U50OWMfg',
    appId: '1:563174569553:web:da0658b463c807ef132a70',
    messagingSenderId: '563174569553',
    projectId: 'btech3-cse',
    authDomain: 'btech3-cse.firebaseapp.com',
    storageBucket: 'btech3-cse.firebasestorage.app',
    measurementId: 'G-SQX3TTZBRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUtDOGSiVRhFWGUkXSFONxPT3sVaCdpk4',
    appId: '1:563174569553:android:77411cacb4019576132a70',
    messagingSenderId: '563174569553',
    projectId: 'btech3-cse',
    storageBucket: 'btech3-cse.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXC5Wf7-Mo5NxhAJuhLgrkWUv_ud6_ThI',
    appId: '1:563174569553:ios:4073ff30395d8595132a70',
    messagingSenderId: '563174569553',
    projectId: 'btech3-cse',
    storageBucket: 'btech3-cse.firebasestorage.app',
    iosClientId: '563174569553-o7e97k4m8giep0ah99i5sqb0v4iu230c.apps.googleusercontent.com',
    iosBundleId: 'com.example.easylearningapp',
  );
}
